version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: passwors
      POSTGRES_DB: accounts
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    build: .
    container_name: node-server
    ports:
      - "3000:3000"
    environment:
      - DATABASE_USER=db_user
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=accounts
    depends_on:
      - db

volumes:
  pg_data:
